version: "3.8"
services:
  backend:
    build:
      context: .
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000
